-- profiles table: Stores public user data, extending auth.users
create table public.profiles (
  id uuid not null primary key references auth.users on delete cascade,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  -- AI creator specific fields
  bio text, -- Creator's biography
  ai_tool_stack text[], -- Array of AI tools, e.g., ['Midjourney', 'Stable Diffusion', 'RunwayML']
  -- Fields for the 3D radar chart
  creativity_score numeric(3, 2) default 0.5, -- e.g., 0.00 to 1.00
  execution_score numeric(3, 2) default 0.5,
  communication_score numeric(3, 2) default 0.5,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.profiles enable row level security;
-- RLS Policies for profiles
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Function to create a profile for a new user
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- jobs table: Stores job postings from clients
create table public.jobs (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.profiles on delete cascade,
  title text not null,
  description text not null,
  status text not null default 'open', -- e.g., 'open', 'in_progress', 'completed', 'cancelled'
  -- Fields for the guided order form
  consistency_level text, -- e.g., 'one-off', 'consistent_style', 'story_driven'
  estimated_duration_days int,
  compute_estimate jsonb, -- Flexible field for compute needs, e.g., {"gpu_hours": 20, "model": "sdxl-1.0"}
  budget numeric(10, 2),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.jobs enable row level security;
-- RLS Policies for jobs
create policy "Jobs are viewable by authenticated users." on jobs for select using (auth.role() = 'authenticated');
create policy "Clients can create jobs." on jobs for insert with check (auth.uid() = client_id);
create policy "Clients can update their own jobs." on jobs for update using (auth.uid() = client_id);

-- orders table: Represents a transaction or agreement between a client and creator(s)
create table public.orders (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs on delete cascade,
  client_id uuid not null references public.profiles on delete cascade,
  final_amount numeric(10, 2),
  status text not null default 'pending', -- e.g., 'pending', 'accepted', 'in_progress', 'delivered', 'completed', 'disputed'
  created_at timestamp with time zone default timezone('utc'::text, now()),
  completed_at timestamp with time zone
);

alter table public.orders enable row level security;
-- RLS Policies for orders
create policy "Users can only see their own orders (as client or part of the team)." on orders for select 
  using (
    auth.uid() = client_id 
    or exists (
      select 1 from public.order_creators oc
      where oc.order_id = id and oc.creator_id = auth.uid()
    )
  );
create policy "Clients can create orders for their jobs." on orders for insert with check (auth.uid() = client_id);

-- Junction table for creators assigned to an order
create table public.order_creators (
  order_id bigint not null references public.orders on delete cascade,
  creator_id uuid not null references public.profiles on delete cascade,
  split_ratio numeric(5, 4) not null check (split_ratio > 0 and split_ratio <= 1),
  primary key (order_id, creator_id)
);

alter table public.order_creators enable row level security;
-- RLS Policies for order_creators
create policy "Involved parties can see order assignments." on order_creators for select 
  using (
    exists (
      select 1 from public.orders 
      where id = order_id and (
        auth.uid() = client_id 
        or auth.uid() = creator_id
      )
    )
  );

-- Function to validate that split ratios for an order do not exceed 1
create or replace function public.validate_split_ratio_sum_on_change()
returns trigger as $$
declare
  total_ratio numeric;
begin
  select sum(split_ratio) into total_ratio
  from public.order_creators
  where order_id = NEW.order_id;

  if total_ratio > 1.0 then
    raise exception 'The sum of split ratios for order_id % cannot exceed 1.0. Current sum is %', NEW.order_id, total_ratio;
  end if;

  return NEW;
end;
$$ language plpgsql;

-- Trigger to enforce split ratio sum constraint on change
create trigger check_split_ratio_on_change
  after insert or update on public.order_creators
  for each row execute procedure public.validate_split_ratio_sum_on_change();

-- Function to validate that split ratios sum to exactly 1 when an order is completed
create or replace function public.validate_splits_on_completion()
returns trigger as $$
declare
  total_ratio numeric;
begin
  if NEW.status = 'completed' and OLD.status <> 'completed' then
    select sum(oc.split_ratio) into total_ratio
    from public.order_creators oc
    where oc.order_id = NEW.id;

    if coalesce(total_ratio, 0) <> 1.0 then
      raise exception 'Cannot complete order %. The sum of split ratios must be exactly 1.0. Current sum is %.', NEW.id, coalesce(total_ratio, 0);
    end if;
  end if;
  return NEW;
end;
$$ language plpgsql;

-- Trigger to check splits when an order is marked as completed
create trigger check_splits_on_completion
  before update on public.orders
  for each row execute procedure public.validate_splits_on_completion();
