-- 1. Create the new 'services' table for productized offerings
create table public.services (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles on delete cascade,
  title text not null,
  description text,
  category text,
  price numeric(10, 2) not null,
  tool_tags text[],
  cover_image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.services enable row level security;

create policy "Services are viewable by everyone." on services for select using (true);
create policy "Creators can manage their own services." on services for all using (auth.uid() = creator_id);


-- 2. Modify the existing 'orders' table for the new service model
alter table public.orders
  drop column job_id,
  add column service_id bigint references public.services on delete set null,
  rename column client_id to buyer_id,
  rename column final_amount to amount;

-- Add a snapshot column to freeze service details at time of purchase
alter table public.orders
  add column service_snapshot jsonb;

-- 3. Update RLS policies for the renamed 'buyer_id'
-- Drop the old policy first
drop policy "Users can only see their own orders (as client or part of the team)." on public.orders;
drop policy "Clients can create orders for their jobs." on public.orders;

-- Create new policies with 'buyer_id'
create policy "Users can view their own orders." on public.orders for select
  using (auth.uid() = buyer_id);

create policy "Users can create their own orders." on public.orders for insert
  with check (auth.uid() = buyer_id);
